---
kind: Secret
apiVersion: v1
metadata:
  name: rook-ceph-external-cluster-details
  namespace: openshift-storage
data:
  external_cluster_details: >-
    W3sibmFtZSI6ICJyb29rLWNlcGgtbW9uLWVuZHBvaW50cyIsICJraW5kIjogIkNvbmZpZ01hcCIsICJkYXRhIjogeyJkYXRhIjogImh5cGVydmlzb3IxPTE5Mi4xOS4xMzAuMTE6Njc4OSIsICJtYXhNb25JZCI6ICIwIiwgIm1hcHBpbmciOiAie30ifX0sIHsibmFtZSI6ICJyb29rLWNlcGgtbW9uIiwgImtpbmQiOiAiU2VjcmV0IiwgImRhdGEiOiB7ImFkbWluLXNlY3JldCI6ICJhZG1pbi1zZWNyZXQiLCAiZnNpZCI6ICI1MThkM2U3YS0xODZiLTQyNzctODRkMi03ZWVmYWNkZjM0NWYiLCAibW9uLXNlY3JldCI6ICJtb24tc2VjcmV0In19LCB7Im5hbWUiOiAicm9vay1jZXBoLW9wZXJhdG9yLWNyZWRzIiwgImtpbmQiOiAiU2VjcmV0IiwgImRhdGEiOiB7InVzZXJJRCI6ICJjbGllbnQub2NwbWdtdC5oZWFsdGhjaGVja2VyIiwgInVzZXJLZXkiOiAiQVFCU0dUTmhreU1WTEJBQU5RUEJiSXIzUkh2Z1VVYm8xWG81U1E9PSJ9fSwgeyJuYW1lIjogInJvb2stY3NpLXJiZC1ub2RlIiwgImtpbmQiOiAiU2VjcmV0IiwgImRhdGEiOiB7InVzZXJJRCI6ICJjc2ktcmJkLW5vZGUiLCAidXNlcktleSI6ICJBUUJydVA1Z3dzdDhGUkFBc1Q1QUhtYWtQU2cxWGs1T3Q4c2Nudz09In19LCB7Im5hbWUiOiAiY2VwaC1yYmQiLCAia2luZCI6ICJTdG9yYWdlQ2xhc3MiLCAiZGF0YSI6IHsicG9vbCI6ICJvY3BtZ210LXJiZCJ9fSwgeyJuYW1lIjogIm1vbml0b3JpbmctZW5kcG9pbnQiLCAia2luZCI6ICJDZXBoQ2x1c3RlciIsICJkYXRhIjogeyJNb25pdG9yaW5nRW5kcG9pbnQiOiAiMTkyLjE5LjEzMC4xMSwxOTIuMTkuMTMwLjEzIiwgIk1vbml0b3JpbmdQb3J0IjogIjkyODMifX0sIHsibmFtZSI6ICJyb29rLWNzaS1yYmQtcHJvdmlzaW9uZXIiLCAia2luZCI6ICJTZWNyZXQiLCAiZGF0YSI6IHsidXNlcklEIjogImNzaS1yYmQtcHJvdmlzaW9uZXIiLCAidXNlcktleSI6ICJBUUJydVA1Z3llaEdGaEFBQTBsaWdEWTZ3WDF3NzB1L2lCd281dz09In19LCB7Im5hbWUiOiAicm9vay1jc2ktY2VwaGZzLXByb3Zpc2lvbmVyIiwgImtpbmQiOiAiU2VjcmV0IiwgImRhdGEiOiB7ImFkbWluSUQiOiAiY3NpLWNlcGhmcy1wcm92aXNpb25lciIsICJhZG1pbktleSI6ICJBUUJydVA1Z1JNditGeEFBUEMwZnpkRHN0V3lhcVc1dlN5d1dlUT09In19LCB7Im5hbWUiOiAicm9vay1jc2ktY2VwaGZzLW5vZGUiLCAia2luZCI6ICJTZWNyZXQiLCAiZGF0YSI6IHsiYWRtaW5JRCI6ICJjc2ktY2VwaGZzLW5vZGUiLCAiYWRtaW5LZXkiOiAiQVFCcnVQNWdiSW9VRnhBQXNpTWI2NW1zeUpSNGZoa0E0akQxZ1E9PSJ9fSwgeyJuYW1lIjogImNlcGhmcyIsICJraW5kIjogIlN0b3JhZ2VDbGFzcyIsICJkYXRhIjogeyJmc05hbWUiOiAiY2VwaGZzIiwgInBvb2wiOiAiY2VwaGZzX2RhdGEifX0sIHsibmFtZSI6ICJjZXBoLXJndyIsICJraW5kIjogIlN0b3JhZ2VDbGFzcyIsICJkYXRhIjogeyJlbmRwb2ludCI6ICIxOTIuMTkuMTMwLjExOjkwMDAiLCAicG9vbFByZWZpeCI6ICJvY3BtZ210LWRlZmF1bHQifX0sIHsibmFtZSI6ICJyZ3ctYWRtaW4tb3BzLXVzZXIiLCAia2luZCI6ICJTZWNyZXQiLCAiZGF0YSI6IHsiYWNjZXNzS2V5IjogIlBZODkzM1daMVNVNVhLNTI2RTVEIiwgInNlY3JldEtleSI6ICJtRWxoQ0JzaUlMbkJ3WmxER2hFNlNEb1I0Skp5YTNKaEJscDdqcmo1In19XQo=
type: Opaque
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-external-storagecluster
  namespace: openshift-storage
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage:
    enable: true
  labelSelector: {}
  managedResources:
    cephBlockPools: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  version: 4.8.0
