---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-telco-shift-zone-cnf-open5gs
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://api.ocpmgmt.lab.diktio.net:6443'
  project: default
  source:
    path: cnf/open5gs
    repoURL: 'https://github.com/nsatsia/telco-gitops.git'
    targetRevision: HEAD
